# Generated by Django 3.1.6 on 2021-03-30 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='book',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
