# Generated by Django 3.1.6 on 2021-03-30 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0002_libro_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='autor_id',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='book',
            new_name='Libro',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='storage_link',
        ),
    ]
