# Generated by Django 3.1.6 on 2021-03-31 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0003_auto_20210330_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='carrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='repisa.carrera'),
        ),
    ]
