# Generated by Django 3.1.6 on 2021-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0004_auto_20210331_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
