# Generated by Django 3.1.6 on 2021-03-31 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0005_auto_20210331_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repisa.carrera'),
        ),
    ]
