# Generated by Django 3.1.6 on 2021-03-31 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0006_auto_20210331_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repisa.carrera'),
        ),
    ]
