# Generated by Django 3.1.6 on 2021-03-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0007_auto_20210331_0247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrera',
            new_name='CarreraT',
        ),
    ]
