# Generated by Django 3.1.6 on 2021-07-13 18:49

import apps.repisa.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0010_auto_20210407_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repisa.carrera'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='Libro',
            field=models.FileField(default='', upload_to=apps.repisa.models.Libro.libros_path),
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('semestre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repisa.semestre')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materia',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='libro',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='repisa.materia'),
        ),
    ]
