# Generated by Django 3.1.6 on 2021-07-14 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0011_auto_20210713_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='semestre',
        ),
    ]
