# Generated by Django 3.1.6 on 2021-07-30 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repisa', '0012_auto_20210714_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='Autor',
            new_name='autor',
        ),
    ]
